"""
Cross-origin MFMCi Server
===================
This is a minimal server for using MFMCi to serve your domain.

:copyright: (C) 2016 by Sean McGregor.
:license:   MIT, see LICENSE for more details.
"""
from flask import Flask, jsonify, request, send_file
from flask.ext.cors import cross_origin
from MFMCi import MFMCi
import importlib
import subprocess
import os
import argparse

print """
Starting Flask Server...
Note, you may be able to specify a domain at this point by adding it as a
positional argument. For examples: `python flask_server.py wildfire`.
"""

parser = argparse.ArgumentParser(description='Start the MFMCi server.')
parser.add_argument('domain', metavar='D', type=str, nargs='?',
                    help='the domain to synthesize trajectories for',
                    default='wildfire')
args = vars(parser.parse_args())

domain_name = args["domain"]
mfmci = MFMCi(domain_name)
policy_module = importlib.import_module("databases." + domain_name + ".policies")
policy_factory = policy_module.policy_factory
annotations = importlib.import_module("databases." + domain_name + ".annotate")
initialization_object = annotations.mdpvis_initialization_object

app = Flask('mfmci', static_folder='.', static_url_path='')

@app.route("/", methods=['GET'])
@cross_origin()
def site_root():
    '''
        This view has CORS enabled for all domains, representing the simplest
        configuration of view-based decoration. You can test this endpoint
        with:

        $ curl --include -X GET http://127.0.0.1:5000/ \
            --header Origin:www.examplesite.com

        Which should return something like:

        >> HTTP/1.0 200 OK
        Content-Type: text/html; charset=utf-8
        Content-Length: 186
        Access-Control-Allow-Origin: www.examplesite.com
        Server: Werkzeug/0.10.4 Python/2.7.9
        Date: Tue, 19 May 2015 17:13:39 GMT

        THE DOCUMENT FOUND BELOW
    '''
    return '''
        <h1>Hello World!</h1>
        <p style='font-size: 150%;'>Your server is running and ready for
        integration.</p>
        <p  style='font-size: 150%;'>To test the other endpoints, visit
          <a href="/initialize">/initialize</a>,
          <a href="/trajectories">/trajectories</a>,
          <a href="/optimize">/optimize</a>, or
          <a href="/state">/state</a>
        '''

@app.route("/initialize", methods=['GET'])
@cross_origin(allow_headers=['Content-Type'])
def cross_origin_initialize():
    '''
        Asks the domain for the parameters to seed the visualization.
    '''
    return jsonify(initialization_object)

@app.route("/trajectories", methods=['GET'])
@cross_origin(allow_headers=['Content-Type'])
def cross_origin_trajectories():
    '''
        Asks the domain for the trajectories generated by the
        requested parameters.
    '''
    count = int(request.args["Sample Count"])
    horizon = int(request.args["Horizon"])

    trajectories = mfmci.get_visualization_trajectories(
        count=count, horizon=horizon,
        policy=policy_factory(request.args)
    )
    json_obj = {"trajectories": trajectories}
    resp = jsonify(json_obj)
    return resp

@app.route("/optimize", methods=['POST','GET'])
@cross_origin(allow_headers=['Content-Type'])
def cross_origin_optimize():
    '''
        Asks the domain to optimize the policy using SMAC.
    '''
    count = int(request.args["Sample Count"])
    horizon = int(request.args["Horizon"])
    runs_limit = int(request.args["Number of Runs Limit"])

    annotations.write_smac_parameters(request.args)
    subprocess.call(
        ['./smac/smac --use-instances false --numberOfRunsLimit ' + str(runs_limit) + ' --pcs-file smac.pcs --algo "python smac.py -domain ' + domain_name + ' -count ' + str(count) + ' -horizon ' + str(horizon) + '" --run-objective QUALITY --rungroup optimizations --seed 1'],
        shell=True)

    directory_listing = os.listdir("smac-output/optimizations/state-run1/")
    out_file = ""
    for file_name in directory_listing:
        if file_name.find("paramstrings-it") == 0:
            out_file = file_name
            break
    f = open("smac-output/optimizations/state-run1/" + out_file, "r")
    last_line = ""
    for line in f:
        last_line = line
    f.close()

    # Example last line of file:
    # 5: days='56', erc='17'
    params = {}
    for param in last_line[last_line.index(" ")+1:].split(" "):
        parts = param.split("=")
        params[parts[0]] = int(parts[1].strip("',").strip("',\n"))

    resp = jsonify(annotations.post_process_smac_output(params))
    return resp

@app.route("/state", methods=['POST','GET'])
@cross_origin(allow_headers=['Content-Type'])
def cross_origin_state():
    '''
        Asks for the image of a particular state.
    '''
    image_file_name = request.args["image"]
    print "sending %s" % image_file_name
    return send_file(annotations.get_image(image_file_name), mimetype='image/jpeg')

# Binds the server to port 8938 and listens to all IP addresses.
if __name__ == "__main__":
    print("Starting server...")
    app.run(host='0.0.0.0', port=8938, debug=True, use_reloader=False, threaded=True)
    print("...started")
